### ISSUE TITLE
Корректно настроить разрешения?

### ISSUE THREAD

**Issue by dsolmann** [Hackathon-on-Internet-freedom/InStorm#1]
Не могу привязать CI, push-ить в проект и создавать ветки, т.к. репозиторий не принадлежит мне/не настроен доступ Maintainer-а

**Comment by wanderer-from** [comment]
у-пс. Пропустил сообщение. Проблема решена?

**Comment by dsolmann** [comment]
@wanderer-from, все еще не могу напрямую коммитить
